/*
 * Ehsan Patel and Colin Grant
 * 1-Apr-2021
 * Shows game statistics for past runs by opening save files, processing the data and displaying
 */
package grantpateljetpackjoyride;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class StatisticsGUI extends javax.swing.JFrame {
    //input stream to read the font file
    private static InputStream is = LoadingGUI.class.getResourceAsStream("fonts/Abel-Regular.ttf");
    //font variables
    private  Font abelFont;
    private static Font scaledAbelFont;
    
    //stores reference to main window to return
    private static MainGUI mainWindow;
    //stores the save address
    private String saveAddress;
    
    //arrays to store the tracked data
    private int[] allCoins;
    private int[] allScores;
    
    //stores the totals
    private int totalDistTravelled;
    private int totalCoinsCollected;
        
    
    /**
     * Creates new form StatisticsGUI
     */
    public StatisticsGUI(MainGUI m, String saveAddress) {
        //stores the save address location
        this.saveAddress = saveAddress;        
        
        //loads in a font to use for the text
        try{
            this.abelFont = Font.createFont(Font.TRUETYPE_FONT, is);
            scaledAbelFont = abelFont.deriveFont(24f);
        }catch(FontFormatException | IOException e){
            System.out.println(e);
        }
        
        //stores the window to go back to
        mainWindow = m;
        //default components for jFrame
        initComponents();
        
        //changes attributes of the display window containing the form
        setTitle("FULLBRICK STUDIOS: Jetpack Joyride");
        ImageIcon icon = new ImageIcon(getClass().getResource("imageResources/costume1/running2.png"));
        setIconImage(icon.getImage());
        setLocationRelativeTo(null);        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backToMenuLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        leaderBoardTextArea = new javax.swing.JTextArea();
        totalDistanceLabel = new javax.swing.JLabel();
        avgDistanceLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        totalCoinsLabel = new javax.swing.JLabel();
        mostCoinsLabel = new javax.swing.JLabel();
        achievementLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1110, 600));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(109, 118, 136));
        jPanel1.setPreferredSize(new java.awt.Dimension(1110, 600));

        backToMenuLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grantpateljetpackjoyride/imageResources/buttons/backFromStats.png"))); // NOI18N
        backToMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backToMenuLabelMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(109, 118, 136));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 255, 255)));

        jLabel2.setBackground(new java.awt.Color(109, 118, 136));
        jLabel2.setFont(scaledAbelFont);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Leaderboard");

        leaderBoardTextArea.setEditable(false);
        leaderBoardTextArea.setBackground(new java.awt.Color(109, 118, 136));
        leaderBoardTextArea.setColumns(20);
        leaderBoardTextArea.setFont(scaledAbelFont);
        leaderBoardTextArea.setForeground(new java.awt.Color(255, 255, 255));
        leaderBoardTextArea.setLineWrap(true);
        leaderBoardTextArea.setRows(5);
        leaderBoardTextArea.setAutoscrolls(false);
        leaderBoardTextArea.setBorder(null);
        leaderBoardTextArea.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        leaderBoardTextArea.setFocusable(false);
        jScrollPane1.setViewportView(leaderBoardTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                .addContainerGap())
        );

        totalDistanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalDistanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalDistanceLabel.setText("Total Distance Travelled: 0");

        avgDistanceLabel.setForeground(new java.awt.Color(255, 255, 255));
        avgDistanceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avgDistanceLabel.setText("Average Distance Travelled: 0");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        totalCoinsLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalCoinsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalCoinsLabel.setText("Total Coins Collected: 0");

        mostCoinsLabel.setForeground(new java.awt.Color(255, 255, 255));
        mostCoinsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostCoinsLabel.setText("Most Coins Collected: 0");

        achievementLabel1.setForeground(new java.awt.Color(255, 255, 255));
        achievementLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        achievementLabel1.setText("Easy as 123...4 Achievement: Not Completed");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("(Scored exactly 1234 in a run)");

        jLabel10.setBackground(new java.awt.Color(109, 118, 136));
        jLabel10.setFont(scaledAbelFont);
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Jetpack Run Analysis");

        jLabel11.setBackground(new java.awt.Color(109, 118, 136));
        jLabel11.setFont(scaledAbelFont);
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Achievement");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(backToMenuLabel)
                .addContainerGap(764, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avgDistanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalDistanceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(411, 411, 411)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(achievementLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalCoinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mostCoinsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backToMenuLabel)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel10)
                        .addGap(29, 29, 29)
                        .addComponent(totalDistanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(avgDistanceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalCoinsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mostCoinsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(achievementLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * runs when the back button/label is clicked by the user
     * @param evt - the click event
     */
    private void backToMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backToMenuLabelMouseClicked
        //set the main window visible again
        ((JFrame)mainWindow.getRootPane().getParent()).setVisible(true);
        //dispose of current window to free up resources
        this.dispose();
    }//GEN-LAST:event_backToMenuLabelMouseClicked

    /**
     * runs when this form comes into focus
     * @param evt - the click event
     */
    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        updateForm();
    }//GEN-LAST:event_formFocusGained

    /**
     * runs if the current form is being shown (usually when switched to)
     * @param evt - the click event
     */
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        //only update form if the form focus did not get triggered
        if(!this.hasFocus()){
            updateForm();
        }
    }//GEN-LAST:event_formComponentShown

    private void updateForm(){
        //reads the file contents (just a lot of numbers) into an array
        allScores = readNumberFile("allScores.jjrs");
        allCoins = readNumberFile("allCoins.jjrs");
        
        //initializes totals
        totalDistTravelled = 0;
        totalCoinsCollected = 0;

        //Error checks that there are numbers that can be processed
        if (allScores != null) {
            //sorts the arrays to be processed, in descending order
            quikDescending(allScores, 0, allScores.length - 1);
            //stores the number of runs for the average
            int numRuns = 0;
            //loops through all the scores
            for (int i = 0; i < allScores.length; ++i) {
                //adds each separate score to the total distance
                totalDistTravelled += allScores[i];
                //adds to the run counter, 1 score in file = 1 run
                ++numRuns;
            }
            //displays the information on distances to the user
            totalDistanceLabel.setText("Total Distance Travelled: " + totalDistTravelled);
            avgDistanceLabel.setText("Average Distance Travelled: " + (totalDistTravelled / numRuns));

            //stores how many scores to show on the leaderboard - can't always read 10 scores if there aren't 10 to read from
            int numLeaderboardValues = Math.min(allScores.length, 10);
            //store a message to display
            String leaderboardMsg = "";
            //iterate through the top scores (10 scores max)
            for (int i = 0; i < numLeaderboardValues; ++i) {
                //adds the score to the leaderboard, with the position on the leaderboard
                leaderboardMsg += (i+1)+". "+allScores[i]+ "\n";
            }
            //updates the leaderboard text area
            leaderBoardTextArea.setText(leaderboardMsg);
            
            //stores the message for whether or not the achievement was completed
            String isCompletedMsg = "Not Completed";
            //searches for numbers that the user has scored
            if(binarySearch(1234, 0, allScores.length)){
                isCompletedMsg = "Completed";
            }
            //sets the text for the achievement label
            achievementLabel1.setText("Easy as 123...4 Achievement: " + isCompletedMsg);

        //display if there was a problem reading the file and return to the main screen
        } else {
            JOptionPane.showMessageDialog(null, "There was a problem reading the file");
            ((JFrame) mainWindow.getRootPane().getParent()).setVisible(true);
            this.dispose();
        }

        //error check to see if the coin data can be processed or not
        if (allCoins != null) {
            //sorts the coins in descending order
            quikDescending(allCoins, 0, allCoins.length - 1);
            //iterates through all the coins collected
            for (int i = 0; i < allCoins.length; ++i) {
                //adds the coins for the run to the total
                totalCoinsCollected += allCoins[i];
            }
            //sets the coin statistics labels
            totalCoinsLabel.setText("Total Coins Collected: " + totalCoinsCollected);
            mostCoinsLabel.setText("Most Coins Collected: " + allCoins[0]);
        //Display error message if the coin file wasn't able to be opened, then return to main screen
        } else {
            JOptionPane.showMessageDialog(null, "There was a problem reading the file");
            ((JFrame) mainWindow.getRootPane().getParent()).setVisible(true);
            this.dispose();
        }
    }
    
    /**
     * Reads the save file into an array of integers
     * @param fileName - the save files where the numbers are located
     */
    private int[] readNumberFile(String fileName){
        //arraylist to store the contents of file could be any number of runs that the user has played
        ArrayList<Integer> fileContents = new ArrayList();
        
        //attempts to read the save file
        try {
            //new input stream for the file
            FileInputStream in = new FileInputStream(saveAddress + fileName);
            //scanner to read the input stream
            Scanner scanner = new Scanner(in);
            
            //adds contents of file into arraylist
            while(scanner.hasNextLine()){
                fileContents.add(Integer.parseInt(scanner.nextLine()));                
            }
            
            //if there are no items in the file, return an array only containing 0
            if(fileContents.isEmpty()){
                return new int[]{0};
            }
            //create an array to return the contents
            int[] nums = new int[fileContents.size()];
            //fill array with contents of arraylist
            for (int i = 0; i < fileContents.size(); ++i) {
                nums[i] = fileContents.get(i);
            }
            //return the array of numbers
            return nums;
        //if the input stream cannot be read
        } catch (IOException e) {
            //show user the error
            JOptionPane.showMessageDialog(null, e);
        }
        //returns a default null, preventing the program from trying to sort and set labels based off the nonexistant array values
        return null;
    }

    /**
     * Uses a quiksort algorithm to arrange items from an array into descending order
     * @param nums - the array to rearrange
     * @param left - the left boundary to sort
     * @param right - the right boundary to sort
     */
    private static void quikDescending(int[] nums, int left, int right){
        //exit condition to prevent more method calls
        if(left >= right){
            return;
        }
        
        //store the left and right in another variable to use and change for looping
        int i = left;
        int j = right;
        
        //the midpoint to switch the values around
        int pivot = nums[(left + right) /2];
        
        //continues to loop until the left and right meet
        while(i < j){
            //increments the left side until the midpoint
            while(nums[i] > pivot){
                //increments the number times a loop was executed
                ++i;
            }
            //increments the right side until the midpoint
            while(nums[j] < pivot){
                //increments the number times a loop was executed
                --j;
            }
            
            //makes a switch if the left is less than the right
            if(i <= j){
                int temp = nums[i];
                nums[i] = nums[j];
                nums[j] = temp;
                //increments i and j so that the sides can meet and the while loop can finish
                ++i;
                --j;
            }
        }

        //quiksorts both sides of the pivot - each element in partition is only sorted relative to pivot value, not to other elements in partition
        quikDescending(nums, left, j);
        quikDescending(nums,i, right);
    }
    
    
    /**
     * Implements a binary search algorithm using recursion
     * Assumes the array being searched is in descending order
     * @param target - the number being searched for
     * @param left - the left bound to search within
     * @param right - the right bound to search within
     */
    private boolean binarySearch(int target, int left, int right){
        //find the middle value to split at
        int middle;
        //if the left side value is bigger than the right, the paths have crossed and the value wasn't found
        if(left > right){
            return false;
        }
        //find the middle value in the array
        middle = (left+right)/2;
        
        //fixes if there is only one number inputted
        if(middle>=allScores.length){
            return false;
        }
        
        //if the middle number happens to be the number being searched for, it can return as being found
        if(allScores[middle] == target){
            return true;
        }
        //if the middle value was larger than the target
        if(allScores[middle] > target){
            //call the function to search the right half of the list
            return binarySearch(target, middle + 1, right);
        //otherwise it is on the left side half
        }else{
            //call the function to search the left half of the list
            return binarySearch(target, left, middle - 1);
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel achievementLabel1;
    private javax.swing.JLabel avgDistanceLabel;
    private javax.swing.JLabel backToMenuLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea leaderBoardTextArea;
    private javax.swing.JLabel mostCoinsLabel;
    private javax.swing.JLabel totalCoinsLabel;
    private javax.swing.JLabel totalDistanceLabel;
    // End of variables declaration//GEN-END:variables
}
